# Generated by Django 2.2.6 on 2019-11-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaculatorMemory',
            new_name='CalculatorMemory',
        ),
    ]
